[package]
name = "rust-ml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rulinalg = "0.4.2"
num = "0.4.1"
csv = "1.3.0"
serde = "1.0.197"
